# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci-with-nodejs

on:
  push:
    branches: ['main']
  pull_request:
    branches:
      - 'bugfix/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
      - 'test/**'
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      # with:
        # https://github.com/pnpm/action-setup?tab=readme-ov-file#install-only-pnpm-with-packagemanager
        # version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    # https://pnpm.io/cli/install#--frozen-lockfile
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm run build
    - name: Upload dist
      if: github.base_ref == 'main'
      uses: actions/upload-artifact@v4
      with:
        name: latest-sample-biomejs-ci
        path: dist
        retention-days: 14
    - name: Test
      run: pnpm run test
